# Website Name
name: Manasulo Maatalu

# Caption
caption: Genuine Thoughts on South Indian Cinema

# Logo
logo: http://revanthkolli.github.io/manasulomaatalu/img/logo.png

# Social Links
footer-links:
  email: contact@manasulomaatalu.com
  facebook: ManasuloMaatalu
  youtube: channel/UCSNmPseStqST0-M19lSE3mw

# Twitter
twitter-username: ManasuloMaatalu

# Disqus Comments
# disqus: revanthkolli-github-io-manasulomaatalu

# Google Analytics
google_analytics:

# local Host
localhost: "127.0.0.1:4000/manasulomaatalu"

# URL
url: https://revanthkolli.github.io/manasulomaatalu/

# URL for Project
baseurl: "/manasulomaatalu"

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
